import { Opportunity } from "../../../shared/schema";

export const opportunities: Opportunity[] = [
  /* Filtered to Bakersfield Only */
  {
    "id": 34,
    "title": "Assistant Environmental Scientist",
    "organization": "Quad-Knopf Inc",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$27 - $32 per hour",
    "requirements": "Technical report writing, Bachelor's degree preferred",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 35,
    "title": "Associate Environmental Scientist",
    "organization": "Quad-Knopf Inc",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$32 - $40 per hour",
    "requirements": "Experience in environmental science, Bachelor's degree",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 36,
    "title": "Environmental Technician",
    "organization": "TRC Companies, Inc.",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$26 - $38 per hour",
    "requirements": "Field work experience, environmental monitoring",
    "benefits": "Competitive benefits",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 37,
    "title": "Environmental Field Technician",
    "organization": "Tetra Tech",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Field Research",
    "salary": "$29 - $33 per hour",
    "requirements": "Field data collection, environmental sampling",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 38,
    "title": "Senior Biologist (Wildlife/Waters Monitoring)",
    "organization": "BRC-Equals3",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Wildlife Biology",
    "salary": "Competitive",
    "requirements": "Experience with wildlife and waters monitoring",
    "benefits": "Not specified",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 39,
    "title": "Corpsmember",
    "organization": "Farmworkers Institute Of Education And Leadership",
    "location": "Bakersfield, CA",
    "type": "Part-time",
    "category": "Conservation Work",
    "salary": "$18 per hour",
    "requirements": "Interest in conservation and community service",
    "benefits": "Training provided",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 40,
    "title": "Environmental Compliance Specialist",
    "organization": "Belshire",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$20 - $22 per hour",
    "requirements": "Knowledge of environmental regulations",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  /* Archived Non-Local Opportunities */
  /*
  {
    "id": 1,
    "title": "Sea Animals Rescue San Diego",
    "organization": "SA Entertainment",
    "location": "San Diego, CA",
    "type": "Full-time, Part-time, Temporary, Contract, Internship",
    "category": "Marine Biology",
    "salary": "$22.60 - $27.22 per hour",
    "requirements": "Prior experience in wildlife rescue, veterinary assistance, or marine biology preferred but not required; training will be provided",
    "benefits": "Referral program, Professional development assistance, Tuition reimbursement, Parental leave, 401(k), Health insurance",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 2,
    "title": "Western Snowy Plover Conservation Technician",
    "organization": "Point Blue Conservation Science",
    "location": "Monterey, CA",
    "type": "Seasonal",
    "category": "Wildlife Conservation",
    "salary": "$23.15 per hour",
    "requirements": "Interest in wildlife conservation and field work",
    "benefits": "Paid sick time",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~200 miles"
  },
  {
    "id": 3,
    "title": "Cetacean Biologists",
    "organization": "SA Entertainment",
    "location": "San Francisco, CA",
    "type": "Full-time",
    "category": "Marine Biology",
    "salary": "Competitive",
    "requirements": "Prior experience with marine mammal research or fieldwork is highly preferred",
    "benefits": "Referral program, Professional development assistance, Tuition reimbursement, Parental leave, 401(k), Health insurance",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 4,
    "title": "Aquarium Curator",
    "organization": "University of California Santa Cruz",
    "location": "Santa Cruz, CA",
    "type": "Full-time",
    "category": "Marine Science",
    "salary": "$33.01 - $42.66 per hour",
    "requirements": "Familiarity with current marine research, experience as marine aquarist, experience collecting and handling marine fish and invertebrates",
    "benefits": "UC Benefits package",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~240 miles"
  },
  {
    "id": 5,
    "title": "Fish and Wildlife Scientific Aid",
    "organization": "California Department of Fish and Wildlife",
    "location": "Monterey County, CA",
    "type": "Non-tenure, Seasonal",
    "category": "Wildlife Science",
    "salary": "$18.26 - $21.67 per hour",
    "requirements": "Good driving record, coursework in biological or chemical sciences, interest in fishing, hunting, or studying fish",
    "benefits": "State benefits",
    "url": "https://wildlife.ca.gov/Employment",
    "distance_from_bakersfield": "~180 miles"
  },
  {
    "id": 6,
    "title": "Work With Sea Animals",
    "organization": "SA Entertainment",
    "location": "San Francisco Bay Area, CA",
    "type": "Full-time",
    "category": "Marine Animal Care",
    "salary": "$24.97 - $30.07 per hour",
    "requirements": "Ability to handle marine animals safely using proper restraint techniques",
    "benefits": "Paid training, Referral program, On-the-job training, Professional development assistance, Tuition reimbursement, Uniform allowance",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~270 miles"
  },
  {
    "id": 7,
    "title": "Dolphins Rescue San Diego",
    "organization": "SA Entertainment",
    "location": "San Diego, CA",
    "type": "Full-time",
    "category": "Marine Conservation",
    "salary": "$22.42 - $27.00 per hour",
    "requirements": "Passionate about marine life conservation and animal welfare",
    "benefits": "Referral program, Professional development assistance, Tuition reimbursement, Parental leave, 401(k), Health insurance",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 8,
    "title": "Animal Husbandry For A Zoo And Aquarium",
    "organization": "SA Entertainment",
    "location": "San Diego, CA",
    "type": "Full-time",
    "category": "Animal Care",
    "salary": "$21.78 - $26.23 per hour",
    "requirements": "Provide exceptional care and management of diverse animal species",
    "benefits": "Referral program, Continuing education credits, Professional development assistance, Tuition reimbursement, Paid parental leave, Uniform allowance",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 9,
    "title": "Research Associate - Genome Editing",
    "organization": "Center for Aquaculture Technologies",
    "location": "San Diego, CA",
    "type": "Full-time",
    "category": "Marine Research",
    "salary": "$51,000 - $59,000 per year",
    "requirements": "Familiarity with computational biology and bioinformatics tools beneficial but not required",
    "benefits": "401(k) matching",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 10,
    "title": "Scott Creek Field Assistant",
    "organization": "University of California Santa Cruz",
    "location": "Santa Cruz, CA",
    "type": "Full-time, Hybrid",
    "category": "Field Research",
    "salary": "$22.58 per hour",
    "requirements": "Assist with field and laboratory studies, travel up to 100% of the time",
    "benefits": "UC Benefits package",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~240 miles"
  },
  {
    "id": 11,
    "title": "Staff Biologist",
    "organization": "True Environmental",
    "location": "San Luis Obispo, CA",
    "type": "Full-time, Hybrid",
    "category": "Environmental Science",
    "salary": "$25 - $34 per hour",
    "requirements": "Help clients navigate and resolve environmental issues",
    "benefits": "Competitive benefits",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~140 miles"
  },
  {
    "id": 12,
    "title": "Fisheries Collaborative Program Specialist",
    "organization": "University of California Santa Cruz",
    "location": "Santa Cruz, CA",
    "type": "Full-time",
    "category": "Fisheries Management",
    "salary": "$53,100 - $188,200 per year",
    "requirements": "Degree in fisheries sciences and management, marine biology and biological oceanography, ocean/marine sciences, oceanography, ecology, or evolutionary biology",
    "benefits": "UC Benefits package",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~240 miles"
  },
  {
    "id": 13,
    "title": "As-Needed Field Biologists (Central Coast)",
    "organization": "Rincon Consultants, Inc",
    "location": "Santa Barbara, CA",
    "type": "Seasonal",
    "category": "Field Biology",
    "salary": "$32 - $65 per hour",
    "requirements": "Bachelor's or Master's degree in biology, botany, ecology, environmental science, or related field",
    "benefits": "Competitive pay",
    "url": "https://www.indeed.com/q-marine-biology-l-california-jobs.html",
    "distance_from_bakersfield": "~150 miles"
  },
  {
    "id": 14,
    "title": "Research Coordinator I, Community Engagement",
    "organization": "San Diego Zoo Wildlife Alliance",
    "location": "Escondido, CA",
    "type": "Permanent",
    "category": "Wildlife Research",
    "salary": "$71,640 per year",
    "requirements": "2-6 years experience",
    "benefits": "Full benefits package",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "~260 miles"
  },
  {
    "id": 15,
    "title": "Botany Intern",
    "organization": "San Diego Natural History Museum",
    "location": "San Diego, CA",
    "type": "Paid Internship",
    "category": "Botany/Conservation",
    "salary": "$20 per hour",
    "requirements": "Interest in botany and natural history",
    "benefits": "Learning experience",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 16,
    "title": "Reforestation Field Technician",
    "organization": "Great Basin Institute",
    "location": "Exeter, CA",
    "type": "Temporary",
    "category": "Conservation/Forestry",
    "salary": "$25 - $27 per hour",
    "requirements": "Interest in reforestation and conservation work",
    "benefits": "Field experience",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "~60 miles"
  },
  {
    "id": 17,
    "title": "Collaborative Forestry Technician",
    "organization": "Sierra Institute for Community and Environment",
    "location": "Taylorsville, CA",
    "type": "Temporary",
    "category": "Forestry/Conservation",
    "salary": "$21 - $25 per hour",
    "requirements": "2-6 years experience",
    "benefits": "Field experience",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "~350 miles"
  },
  {
    "id": 18,
    "title": "Public Affairs Intern",
    "organization": "Midpeninsula Regional Open Space District",
    "location": "Los Altos, CA",
    "type": "Paid Internship",
    "category": "Conservation Management",
    "salary": "$27.13 per hour",
    "requirements": "Interest in public affairs and conservation",
    "benefits": "Professional development",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "~250 miles"
  },
  {
    "id": 19,
    "title": "Marine Mammal Center Volunteer",
    "organization": "The Marine Mammal Center",
    "location": "Sausalito, CA",
    "type": "Volunteer",
    "category": "Marine Mammal Care",
    "salary": "Volunteer",
    "requirements": "Attend 2-day training series, commit to at least 8 hours per month, 18+ years old",
    "benefits": "Training in marine mammal care, ocean health education",
    "url": "https://www.marinemammalcenter.org/get-involved/volunteer/sausalito",
    "distance_from_bakersfield": "~290 miles"
  },
  {
    "id": 20,
    "title": "Monterey Bay Aquarium Volunteer Guide",
    "organization": "Monterey Bay Aquarium",
    "location": "Monterey, CA",
    "type": "Volunteer",
    "category": "Ocean Education",
    "salary": "Volunteer",
    "requirements": "Passionate about ocean conservation, attend info session and training",
    "benefits": "Training in ocean conservation, public education experience",
    "url": "https://www.montereybayaquarium.org/join-give/become-a-volunteer",
    "distance_from_bakersfield": "~200 miles"
  },
  {
    "id": 21,
    "title": "Pacific Marine Mammal Center Volunteer",
    "organization": "Pacific Marine Mammal Center",
    "location": "Laguna Beach, CA",
    "type": "Volunteer",
    "category": "Animal Care",
    "salary": "Volunteer",
    "requirements": "Interest in marine mammal care and ocean stewardship",
    "benefits": "Hands-on animal care experience",
    "url": "https://www.pacificmmc.org/volunteer",
    "distance_from_bakersfield": "~230 miles"
  },
  {
    "id": 22,
    "title": "UC Davis Coastal Marine Science Volunteer",
    "organization": "UC Davis Coastal and Marine Sciences Institute",
    "location": "Bodega Bay, CA",
    "type": "Volunteer",
    "category": "Marine Science",
    "salary": "Volunteer",
    "requirements": "Interest in marine biology and husbandry",
    "benefits": "Experience with marine biota care for science and education",
    "url": "https://marinescience.ucdavis.edu/about/volunteer-opportunities",
    "distance_from_bakersfield": "~320 miles"
  },
  {
    "id": 23,
    "title": "Catalina Island Conservation Intern",
    "organization": "Catalina Island Conservancy",
    "location": "Catalina Island, CA",
    "type": "Internship",
    "category": "Conservation Biology",
    "salary": "Stipend provided",
    "requirements": "Entry-level professionals with backgrounds in conservation, biology, or related fields",
    "benefits": "Housing provided, hands-on conservation experience",
    "url": "https://catalinaconservancy.org/conservation/internships/",
    "distance_from_bakersfield": "~240 miles"
  },
  {
    "id": 24,
    "title": "Ocean Institute Volunteer",
    "organization": "Ocean Institute",
    "location": "Dana Point, CA",
    "type": "Volunteer",
    "category": "Ocean Education",
    "salary": "Volunteer",
    "requirements": "Interest in ocean education and hands-on teaching",
    "benefits": "Training in ocean science education",
    "url": "https://oceaninstitute.org/volunteer-opportunities/",
    "distance_from_bakersfield": "~240 miles"
  },
  {
    "id": 25,
    "title": "Aquarium of the Pacific Volunteer",
    "organization": "Aquarium of the Pacific",
    "location": "Long Beach, CA",
    "type": "Volunteer",
    "category": "Marine Education",
    "salary": "Volunteer",
    "requirements": "Interest in marine life and public education",
    "benefits": "Diverse volunteer roles from guest services to diving with fish",
    "url": "https://www.aquariumofpacific.org/volunteer",
    "distance_from_bakersfield": "~150 miles"
  },
  {
    "id": 26,
    "title": "California State Parks Ranger",
    "organization": "California State Parks",
    "location": "Various locations statewide",
    "type": "Full-time",
    "category": "Park Management",
    "salary": "Competitive state salary",
    "requirements": "Pass State Park Peace Officer exam, background check",
    "benefits": "State benefits, retirement, health insurance",
    "url": "https://www.parks.ca.gov/jobs",
    "distance_from_bakersfield": "Varies"
  },
  {
    "id": 27,
    "title": "NOAA Fisheries Positions",
    "organization": "NOAA Fisheries West Coast",
    "location": "Various CA locations",
    "type": "Full-time, Internships",
    "category": "Fisheries Science",
    "salary": "Federal pay scale",
    "requirements": "Varies by position - biology, ecology, marine science backgrounds",
    "benefits": "Federal benefits package",
    "url": "https://www.fisheries.noaa.gov/west-coast/careers-more/job-openings-fisheries-ecology-division",
    "distance_from_bakersfield": "Varies"
  },
  {
    "id": 28,
    "title": "California Conservation Corps Member",
    "organization": "California Conservation Corps",
    "location": "Various locations including Eureka, CA",
    "type": "Temporary",
    "category": "Conservation Work",
    "salary": "$5,931 - $7,366 per month",
    "requirements": "18-25 years old (up to 30 for veterans), California resident",
    "benefits": "Housing, meals, education awards, job training",
    "url": "https://www.conservationjobboard.com/california",
    "distance_from_bakersfield": "Varies"
  },
  {
    "id": 29,
    "title": "Wildlife Rehabilitation Intern",
    "organization": "Various Wildlife Centers",
    "location": "Throughout California",
    "type": "Internship",
    "category": "Wildlife Care",
    "salary": "Varies, often unpaid with stipend",
    "requirements": "Interest in wildlife rehabilitation, coursework in biology or related field",
    "benefits": "Hands-on wildlife care experience",
    "url": "https://www.indeed.com/q-internship-wildlife-l-california-jobs.html",
    "distance_from_bakersfield": "Varies"
  },
  {
    "id": 30,
    "title": "American Conservation Experience (ACE) EPIC Program",
    "organization": "American Conservation Experience",
    "location": "Various locations nationwide including CA",
    "type": "Internship/Fellowship",
    "category": "Conservation",
    "salary": "Stipend provided",
    "requirements": "Ages 18-30 (up to 35 for veterans), interest in conservation",
    "benefits": "Hands-on conservation experience, networking, potential housing",
    "url": "https://www.usaconservation.org/epic/",
    "distance_from_bakersfield": "Varies"
  },
  {
    "id": 31,
    "title": "Oakland Zoo Volunteer/Intern",
    "organization": "Oakland Zoo",
    "location": "Oakland, CA",
    "type": "Volunteer/Internship",
    "category": "Zoo Education",
    "salary": "Volunteer/Stipend",
    "requirements": "Teen and adult opportunities available",
    "benefits": "Education and maintenance team experience",
    "url": "https://www.oaklandzoo.org/volunteer-and-internship-opportunities",
    "distance_from_bakersfield": "~280 miles"
  },
  {
    "id": 32,
    "title": "Save Our Shores Sanctuary Stewards",
    "organization": "Save Our Shores",
    "location": "Monterey Bay area, CA",
    "type": "Volunteer",
    "category": "Marine Conservation",
    "salary": "Volunteer",
    "requirements": "Interest in marine protected areas and citizen action",
    "benefits": "Training in marine conservation advocacy",
    "url": "https://californiampas.org/volunteer",
    "distance_from_bakersfield": "~200 miles"
  },
  {
    "id": 33,
    "title": "Cabrillo Marine Aquarium Volunteer",
    "organization": "City of Los Angeles Recreation and Parks",
    "location": "San Pedro, CA",
    "type": "Volunteer",
    "category": "Marine Husbandry",
    "salary": "Volunteer",
    "requirements": "Interest in marine fish, sharks, octopuses care and maintenance",
    "benefits": "Hands-on husbandry experience with local SoCal marine life",
    "url": "https://cma.recreation.parks.lacity.gov/get-involved/volunteer-programs",
    "distance_from_bakersfield": "~130 miles"
  }
  */
];

/*
  {
    "id": 34,
    "title": "Assistant Environmental Scientist",
    "organization": "Quad-Knopf Inc",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$27 - $32 per hour",
    "requirements": "Technical report writing, Bachelor's degree preferred",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 35,
    "title": "Associate Environmental Scientist",
    "organization": "Quad-Knopf Inc",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$32 - $40 per hour",
    "requirements": "Experience in environmental science, Bachelor's degree",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 36,
    "title": "Environmental Technician",
    "organization": "TRC Companies, Inc.",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$26 - $38 per hour",
    "requirements": "Field work experience, environmental monitoring",
    "benefits": "Competitive benefits",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 37,
    "title": "Environmental Field Technician",
    "organization": "Tetra Tech",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Field Research",
    "salary": "$29 - $33 per hour",
    "requirements": "Field data collection, environmental sampling",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 38,
    "title": "Senior Biologist (Wildlife/Waters Monitoring)",
    "organization": "BRC-Equals3",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Wildlife Biology",
    "salary": "Competitive",
    "requirements": "Experience with wildlife and waters monitoring",
    "benefits": "Not specified",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 39,
    "title": "Corpsmember",
    "organization": "Farmworkers Institute Of Education And Leadership",
    "location": "Bakersfield, CA",
    "type": "Part-time",
    "category": "Conservation Work",
    "salary": "$18 per hour",
    "requirements": "Interest in conservation and community service",
    "benefits": "Training provided",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
    "distance_from_bakersfield": "0 miles"
  },
  {
    "id": 40,
    "title": "Environmental Compliance Specialist",
    "organization": "Belshire",
    "location": "Bakersfield, CA",
    "type": "Full-time",
    "category": "Environmental Science",
    "salary": "$20 - $22 per hour",
    "requirements": "Knowledge of environmental regulations",
    "benefits": "Full benefits package",
    "url": "https://www.indeed.com/q-conservation-l-bakersfield,-ca-jobs.html",
     "distance_from_bakersfield": "0 miles"
  }
  */
